### ISSUE TITLE
Adding options about cursor

### ISSUE THREAD

**Issue by smallshen** [heroslender/menu-framework#8]
Adding some options about cursor, such as disable the cursor, or change the cursor delay

**Comment by heroslender** [comment]
I have implemented that already, see #7 for the option to [disable the cursor](https://github.com/heroslender/menu-framework/blob/4f644a33e95c5c90180d7015d3439320ca608c7b/bukkit/src/main/kotlin/com/heroslender/hmf/bukkit/screen/tracker/cursor/StaticCursorTracker.kt). The logic is there, now I just need to extend it a bit further to allow for more configuration options.
The cursor delay can be changed through the [BukkitMenuManager options](https://github.com/heroslender/menu-framework/blob/4f644a33e95c5c90180d7015d3439320ca608c7b/bukkit/src/main/kotlin/com/heroslender/hmf/bukkit/manager/impl/BukkitMenuManagerImpl.kt#L227).
